# Generated by Django 3.1.7 on 2021-03-23 13:28

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('percent', models.PositiveSmallIntegerField(default=0, help_text='Добавочный процент от закупочной стоимости', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Процент наценки')),
                ('min_percent', models.PositiveSmallIntegerField(blank=True, help_text='Минимальный добавочный процент от закупочной стоимости', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Минимальный Процент наценки')),
                ('description', models.CharField(blank=True, help_text='Краткое описание товара', max_length=600, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, help_text='Дата, когда товар был добавлен в базу', verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('OUTCOME', 'OUTCOME'), ('INCOME', 'INCOME')], max_length=12, verbose_name='Тип')),
                ('sum', models.PositiveIntegerField(verbose_name='Цена')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата, когда товар был добавлен в базу', verbose_name='Дата публикации')),
                ('last_change', models.DateTimeField(auto_now_add=True, help_text='Дата, когда товар был редактирован', verbose_name='Дата изменении')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
                ('items', models.ManyToManyField(blank=True, related_name='trans', to='app.Item', verbose_name='цены Товаров')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
