# Generated by Django 3.1.7 on 2021-03-22 07:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('percent', models.PositiveSmallIntegerField(default=0, help_text='Добавочный процент от закупочной стоимости', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Процент наценки')),
                ('min_percent', models.PositiveSmallIntegerField(blank=True, help_text='Минимальный добавочный процент от закупочной стоимости', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Минимальный Процент наценки')),
                ('description', models.CharField(blank=True, help_text='Краткое описание товара', max_length=600, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, help_text='Дата, когда товар был добавлен в базу', verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='TypeIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Наименование')),
                ('sum', models.PositiveIntegerField(verbose_name='Цена')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата, когда товар был добавлен в базу', verbose_name='Дата публикации')),
                ('item', models.ManyToManyField(to='app.Item', verbose_name='цены Товаров')),
                ('type_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typein', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
