# Generated by Django 3.1.7 on 2021-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение Товара', null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
