# Generated by Django 3.1.7 on 2021-03-25 06:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210324_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Изображение Товара', upload_to='images', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='min_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Минимальный добавочный процент от закупочной стоимости', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный Процент наценки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='percent',
            field=models.PositiveSmallIntegerField(verbose_name='Процент наценки'),
        ),
    ]
