# Generated by Django 3.1.7 on 2021-04-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
